#############################################################################
# Makefile for building: Asteroid
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Sep 12 13:57:49 2021
# Project:  Asteroid.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -o Makefile Asteroid.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/phonon -I/usr/include -I. -I/usr/include/phonon_compat -ITemp
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lphonon -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = Temp/

####### Files

SOURCES       = About.cpp \
		Arena.cpp \
		Asteroid.cpp \
		Engine.cpp \
		Game.cpp \
		Objects.cpp Temp/moc_About.cpp \
		Temp/moc_Arena.cpp \
		Temp/moc_Game.cpp \
		Temp/qrc_Image.cpp
OBJECTS       = Temp/About.o \
		Temp/Arena.o \
		Temp/Asteroid.o \
		Temp/Engine.o \
		Temp/Game.o \
		Temp/Objects.o \
		Temp/moc_About.o \
		Temp/moc_Arena.o \
		Temp/moc_Game.o \
		Temp/qrc_Image.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		Asteroid.pro
QMAKE_TARGET  = Asteroid
DESTDIR       = 
TARGET        = Asteroid

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Asteroid.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile Asteroid.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Asteroid.pro

dist: 
	@$(CHK_DIR_EXISTS) Temp/Asteroid1.0.0 || $(MKDIR) Temp/Asteroid1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) Temp/Asteroid1.0.0/ && $(COPY_FILE) --parents About.h Arena.h Engine.h Game.h Objects.h Version.h Temp/Asteroid1.0.0/ && $(COPY_FILE) --parents Image.qrc Temp/Asteroid1.0.0/ && $(COPY_FILE) --parents About.cpp Arena.cpp Asteroid.cpp Engine.cpp Game.cpp Objects.cpp Temp/Asteroid1.0.0/ && (cd `dirname Temp/Asteroid1.0.0` && $(TAR) Asteroid1.0.0.tar Asteroid1.0.0 && $(COMPRESS) Asteroid1.0.0.tar) && $(MOVE) `dirname Temp/Asteroid1.0.0`/Asteroid1.0.0.tar.gz . && $(DEL_FILE) -r Temp/Asteroid1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: Temp/moc_About.cpp Temp/moc_Arena.cpp Temp/moc_Game.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) Temp/moc_About.cpp Temp/moc_Arena.cpp Temp/moc_Game.cpp
Temp/moc_About.cpp: About.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) About.h -o Temp/moc_About.cpp

Temp/moc_Arena.cpp: Arena.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) Arena.h -o Temp/moc_Arena.cpp

Temp/moc_Game.cpp: Engine.h \
		Objects.h \
		Game.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) Game.h -o Temp/moc_Game.cpp

compiler_rcc_make_all: Temp/qrc_Image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) Temp/qrc_Image.cpp
Temp/qrc_Image.cpp: Image.qrc \
		Artwork.png \
		Icon32.png
	/usr/lib64/qt4/bin/rcc -name Image Image.qrc -o Temp/qrc_Image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Temp/About.o: About.cpp About.h \
		Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/About.o About.cpp

Temp/Arena.o: Arena.cpp Arena.h \
		Version.h \
		About.h \
		Game.h \
		Engine.h \
		Objects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/Arena.o Arena.cpp

Temp/Asteroid.o: Asteroid.cpp Arena.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/Asteroid.o Asteroid.cpp

Temp/Engine.o: Engine.cpp Engine.h \
		Objects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/Engine.o Engine.cpp

Temp/Game.o: Game.cpp Game.h \
		Engine.h \
		Objects.h \
		Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/Game.o Game.cpp

Temp/Objects.o: Objects.cpp Objects.h \
		Engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/Objects.o Objects.cpp

Temp/moc_About.o: Temp/moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/moc_About.o Temp/moc_About.cpp

Temp/moc_Arena.o: Temp/moc_Arena.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/moc_Arena.o Temp/moc_Arena.cpp

Temp/moc_Game.o: Temp/moc_Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/moc_Game.o Temp/moc_Game.cpp

Temp/qrc_Image.o: Temp/qrc_Image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Temp/qrc_Image.o Temp/qrc_Image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

